name: Build and Release

on:
  push:
    tags:
      - "*"

jobs:
  build:
    name: Build Project
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '7.0.x'

      - name: Get current date
        id: current_date
        run: echo "RELEASE_DATE=$(date +'%Y.%m.%d.%H%M')" >> $GITHUB_ENV

      - name: Update version in C# code
        run: |
          sed -i "s|public const string VERSION = \".*\";|public const string VERSION = \"${{ env.RELEASE_DATE }}\";|g" app/GNSSStatus/Program.cs


      - name: Restore dependencies
        run: dotnet restore app/GNSSStatus.sln

      - name: Build project
        run: dotnet publish app/GNSSStatus.sln -r linux-arm64 -c Release --self-contained false /p:PublishSingleFile=true

      - name: Archive build output
        uses: actions/upload-artifact@v4
        with:
          name: GNSSStatus
          path: app/Build/Release/net7.0/linux-arm64/publish
        
  release:
    name: Create GitHub Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: GNSSStatus

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          draft: false
          prerelease: false
          files: |
            app/Build/Release/net7.0/linux-arm64/publish/GNSSStatus
            app/Build/Release/net7.0/linux-arm64/publish/assets/FIN2005N00.lst
