name: Build and Release

on:
  push:
    tags:
      - "*"

permissions:
  contents: write

jobs:
  build:
    name: Build Project
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '7.0.x'

      - name: Update version in C# code
        run: |
          sed -i "s|public const string VERSION = \".*\";|public const string VERSION = \"${{ github.ref }}\";|g" app/GNSSStatus/Program.cs


      - name: Restore dependencies
        run: dotnet restore app/GNSSStatus.sln

      - name: Build project
        run: dotnet publish app/GNSSStatus.sln -r linux-arm64 -c Release --self-contained false /p:PublishSingleFile=true

      - name: Archive build output
        uses: actions/upload-artifact@v4
        with:
          name: GNSSStatus
          path: app/Build/Release/net7.0/linux-arm64/publish
        
  release:
    name: Create GitHub Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: GNSSStatus
      
      # Execute "ls" command to list the files in the artifact
      - name: List files in artifact
        run: ls

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: false
          prerelease: false
          fail_on_unmatched_files: true
          files: |
            /home/runner/work/GNSSStatus/GNSSStatus/app/Build/Release/net7.0/linux-arm64/publish/*